### ISSUE TITLE
Is this course ready for primetime?

### ISSUE THREAD

**Issue by avahoffman** [fhdsl/AI_for_Decision_Makers#6]
If not, I'd take off either the description or link so it's not rendered as part of DaSL Collection.

![image](https://github.com/fhdsl/AI_for_Decision_Makers/assets/15618412/74ce558d-d548-47da-a89d-af3473b3e64b)

ping @ehumph

**Comment by ehumph** [comment]
Good point - both are removed until it is ready.

**Comment by avahoffman** [comment]
ok thanks for confirming!
